666.59998 ^D1_Feed @!
666.59998 ^D2_Feed @!
666.59998 ^D3_Feed @!
666.59998 ^D4_Feed @!
666.59998 ^D5_Feed @!
450.00000 ^D6_Feed @!
24.000000 ^F1_pulses @!
24.000000 ^F2_pulses @!
24.000000 ^F4_pulses @!
\ ""DOWNLOAD_COMPRESSION_OFF
*D1txt $INN
file:a,C:\Users\Digester\Documents\Shed_Digester1.txt
*D2txt $INN
file:a,C:\Users\Digester\Documents\Shed_Digester2.txt
*D3txt $INN
file:a,C:\Users\Digester\Documents\Shed_Digester3.txt
